//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sa.gov.libgph.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PotPhotographyRequest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PotPhotographyRequest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sa.gov.libgph.Resources.PotPhotographyRequest", typeof(PotPhotographyRequest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary Qualification.
        /// </summary>
        public static string BeneficiaryQualification {
            get {
                return ResourceManager.GetString("BeneficiaryQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Title.
        /// </summary>
        public static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Use Characters only.
        /// </summary>
        public static string Charactersonly {
            get {
                return ResourceManager.GetString("Charactersonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Page.
        /// </summary>
        public static string EndPage {
            get {
                return ResourceManager.GetString("EndPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Book Title.
        /// </summary>
        public static string MaxBookTitle {
            get {
                return ResourceManager.GetString("MaxBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message Must Be Maximum 500 Character.
        /// </summary>
        public static string MaxMessage {
            get {
                return ResourceManager.GetString("MaxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Full Name Must Be Maximum 50 Character.
        /// </summary>
        public static string MaxName {
            get {
                return ResourceManager.GetString("MaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Subject Must Be Maximum 100 Character.
        /// </summary>
        public static string MaxSubject {
            get {
                return ResourceManager.GetString("MaxSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Book Title.
        /// </summary>
        public static string MinBookTitle {
            get {
                return ResourceManager.GetString("MinBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message Must Be at Least 10 Character.
        /// </summary>
        public static string MinMessage {
            get {
                return ResourceManager.GetString("MinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Full Name Must Be at Least 5 Character.
        /// </summary>
        public static string MinName {
            get {
                return ResourceManager.GetString("MinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Subject Must Be at Least 10 Character.
        /// </summary>
        public static string MinSubject {
            get {
                return ResourceManager.GetString("MinSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Beneficiary Qualification.
        /// </summary>
        public static string RequiredBeneficiaryQualification {
            get {
                return ResourceManager.GetString("RequiredBeneficiaryQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Book Title.
        /// </summary>
        public static string RequiredBookTitle {
            get {
                return ResourceManager.GetString("RequiredBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please! Enter your Email.
        /// </summary>
        public static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required End Page.
        /// </summary>
        public static string RequiredEndPage {
            get {
                return ResourceManager.GetString("RequiredEndPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please! Enter your Question.
        /// </summary>
        public static string RequiredMessage {
            get {
                return ResourceManager.GetString("RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please! Enter your Phone Number.
        /// </summary>
        public static string RequiredMobile {
            get {
                return ResourceManager.GetString("RequiredMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please! Enter your Name.
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rquired Start Page.
        /// </summary>
        public static string RequiredStartPage {
            get {
                return ResourceManager.GetString("RequiredStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        public static string StartPage {
            get {
                return ResourceManager.GetString("StartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Country.
        /// </summary>
        public static string ValidateCountry {
            get {
                return ResourceManager.GetString("ValidateCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email is invalid,Please! Check it again.
        /// </summary>
        public static string ValidateEmail {
            get {
                return ResourceManager.GetString("ValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Phone Number is invalid, Please! Check it again.
        /// </summary>
        public static string ValidateMobile {
            get {
                return ResourceManager.GetString("ValidateMobile", resourceCulture);
            }
        }
    }
}
