//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sa.gov.libgph.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestToDepositAScientificThesis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestToDepositAScientificThesis() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sa.gov.libgph.Resources.RequestToDepositAScientificThesis", typeof(RequestToDepositAScientificThesis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Name.
        /// </summary>
        public static string ApplicantName {
            get {
                return ResourceManager.GetString("ApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arabicExtractFile.
        /// </summary>
        public static string arabicExtractFile {
            get {
                return ResourceManager.GetString("arabicExtractFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvailabilityType.
        /// </summary>
        public static string AvailabilityType {
            get {
                return ResourceManager.GetString("AvailabilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available.
        /// </summary>
        public static string available {
            get {
                return ResourceManager.GetString("available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إتاحة العنوان + فهرس الموضوعات فقط.
        /// </summary>
        public static string availType1 {
            get {
                return ResourceManager.GetString("availType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إتاحة العنوان + فهرس الموضوعات 9 المستخلص بالعربي + المستخلص بالإنجليزي.
        /// </summary>
        public static string availType2 {
            get {
                return ResourceManager.GetString("availType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إتاحة العنوان + فهرس الموضوعات 9 المستخلص بالعربي + المستخلص بالإنجليزي + المقدمة.
        /// </summary>
        public static string availType3 {
            get {
                return ResourceManager.GetString("availType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إتاحة العنوان + فهرس الموضوعات 9 المستخلص بالعربي + المستخلص بالإنجليزي + المقدمة + 25% من الرسالة.
        /// </summary>
        public static string availType4 {
            get {
                return ResourceManager.GetString("availType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallNum.
        /// </summary>
        public static string CallNum {
            get {
                return ResourceManager.GetString("CallNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collectionFile.
        /// </summary>
        public static string collectionFile {
            get {
                return ResourceManager.GetString("collectionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to englishExtractFile.
        /// </summary>
        public static string englishExtractFile {
            get {
                return ResourceManager.GetString("englishExtractFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string Faculty {
            get {
                return ResourceManager.GetString("Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to introFile.
        /// </summary>
        public static string introFile {
            get {
                return ResourceManager.GetString("introFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsArchived.
        /// </summary>
        public static string IsArchived {
            get {
                return ResourceManager.GetString("IsArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAvailable.
        /// </summary>
        public static string IsAvailable {
            get {
                return ResourceManager.GetString("IsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAvailableWithChains.
        /// </summary>
        public static string IsAvailableWithChains {
            get {
                return ResourceManager.GetString("IsAvailableWithChains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not available.
        /// </summary>
        public static string notavailable {
            get {
                return ResourceManager.GetString("notavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfPages.
        /// </summary>
        public static string NumberOfPages {
            get {
                return ResourceManager.GetString("NumberOfPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfParts.
        /// </summary>
        public static string NumberOfParts {
            get {
                return ResourceManager.GetString("NumberOfParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF or Word Files only Allowed.
        /// </summary>
        public static string PDForWordFilesValidation {
            get {
                return ResourceManager.GetString("PDForWordFilesValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quarterCollectionFile.
        /// </summary>
        public static string quarterCollectionFile {
            get {
                return ResourceManager.GetString("quarterCollectionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestStatusId.
        /// </summary>
        public static string RequestStatusId {
            get {
                return ResourceManager.GetString("RequestStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredApplicantName.
        /// </summary>
        public static string RequiredApplicantName {
            get {
                return ResourceManager.GetString("RequiredApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredarabicExtractFile.
        /// </summary>
        public static string RequiredarabicExtractFile {
            get {
                return ResourceManager.GetString("RequiredarabicExtractFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredAvailabilityType.
        /// </summary>
        public static string RequiredAvailabilityType {
            get {
                return ResourceManager.GetString("RequiredAvailabilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredCallNum.
        /// </summary>
        public static string RequiredCallNum {
            get {
                return ResourceManager.GetString("RequiredCallNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredcollectionFile.
        /// </summary>
        public static string RequiredcollectionFile {
            get {
                return ResourceManager.GetString("RequiredcollectionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Country.
        /// </summary>
        public static string RequiredCountry {
            get {
                return ResourceManager.GetString("RequiredCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredDepartment.
        /// </summary>
        public static string RequiredDepartment {
            get {
                return ResourceManager.GetString("RequiredDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredenglishExtractFile.
        /// </summary>
        public static string RequiredenglishExtractFile {
            get {
                return ResourceManager.GetString("RequiredenglishExtractFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredFaculty.
        /// </summary>
        public static string RequiredFaculty {
            get {
                return ResourceManager.GetString("RequiredFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredInstructions.
        /// </summary>
        public static string RequiredInstructions {
            get {
                return ResourceManager.GetString("RequiredInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredintroFile.
        /// </summary>
        public static string RequiredintroFile {
            get {
                return ResourceManager.GetString("RequiredintroFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredIsArchived.
        /// </summary>
        public static string RequiredIsArchived {
            get {
                return ResourceManager.GetString("RequiredIsArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredIsAvailable.
        /// </summary>
        public static string RequiredIsAvailable {
            get {
                return ResourceManager.GetString("RequiredIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredIsAvailableWithChains.
        /// </summary>
        public static string RequiredIsAvailableWithChains {
            get {
                return ResourceManager.GetString("RequiredIsAvailableWithChains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredMobile.
        /// </summary>
        public static string RequiredMobile {
            get {
                return ResourceManager.GetString("RequiredMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredNumberOfPages.
        /// </summary>
        public static string RequiredNumberOfPages {
            get {
                return ResourceManager.GetString("RequiredNumberOfPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredNumberOfParts.
        /// </summary>
        public static string RequiredNumberOfParts {
            get {
                return ResourceManager.GetString("RequiredNumberOfParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredquarterCollectionFile.
        /// </summary>
        public static string RequiredquarterCollectionFile {
            get {
                return ResourceManager.GetString("RequiredquarterCollectionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredReasonOfRejection.
        /// </summary>
        public static string RequiredReasonOfRejection {
            get {
                return ResourceManager.GetString("RequiredReasonOfRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredRequestStatusId.
        /// </summary>
        public static string RequiredRequestStatusId {
            get {
                return ResourceManager.GetString("RequiredRequestStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredScientificDegree.
        /// </summary>
        public static string RequiredScientificDegree {
            get {
                return ResourceManager.GetString("RequiredScientificDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredsubjectsIndexFile.
        /// </summary>
        public static string RequiredsubjectsIndexFile {
            get {
                return ResourceManager.GetString("RequiredsubjectsIndexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredThesisData.
        /// </summary>
        public static string RequiredThesisData {
            get {
                return ResourceManager.GetString("RequiredThesisData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredthesisFile.
        /// </summary>
        public static string RequiredthesisFile {
            get {
                return ResourceManager.GetString("RequiredthesisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredThesisTitle.
        /// </summary>
        public static string RequiredThesisTitle {
            get {
                return ResourceManager.GetString("RequiredThesisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredthesisTitleFile.
        /// </summary>
        public static string RequiredthesisTitleFile {
            get {
                return ResourceManager.GetString("RequiredthesisTitleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredUniversityId.
        /// </summary>
        public static string RequiredUniversityId {
            get {
                return ResourceManager.GetString("RequiredUniversityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredUniversityNameOutsideKingdom.
        /// </summary>
        public static string RequiredUniversityNameOutsideKingdom {
            get {
                return ResourceManager.GetString("RequiredUniversityNameOutsideKingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredYearOfDiscussion.
        /// </summary>
        public static string RequiredYearOfDiscussion {
            get {
                return ResourceManager.GetString("RequiredYearOfDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScientificDegree.
        /// </summary>
        public static string ScientificDegree {
            get {
                return ResourceManager.GetString("ScientificDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subjectsIndexFile.
        /// </summary>
        public static string subjectsIndexFile {
            get {
                return ResourceManager.GetString("subjectsIndexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThesisData.
        /// </summary>
        public static string ThesisData {
            get {
                return ResourceManager.GetString("ThesisData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thesisFile.
        /// </summary>
        public static string thesisFile {
            get {
                return ResourceManager.GetString("thesisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThesisTitle.
        /// </summary>
        public static string ThesisTitle {
            get {
                return ResourceManager.GetString("ThesisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thesisTitleFile.
        /// </summary>
        public static string thesisTitleFile {
            get {
                return ResourceManager.GetString("thesisTitleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniversityId.
        /// </summary>
        public static string UniversityId {
            get {
                return ResourceManager.GetString("UniversityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University Name Outside Kingdom.
        /// </summary>
        public static string UniversityNameOutsideKingdom {
            get {
                return ResourceManager.GetString("UniversityNameOutsideKingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YearOfDiscussion.
        /// </summary>
        public static string YearOfDiscussion {
            get {
                return ResourceManager.GetString("YearOfDiscussion", resourceCulture);
            }
        }
    }
}
