//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sa.gov.libgph.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuggestingBuyingAbook {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuggestingBuyingAbook() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sa.gov.libgph.Resources.SuggestingBuyingAbook", typeof(SuggestingBuyingAbook).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Name.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Type.
        /// </summary>
        public static string BookTypeId {
            get {
                return ResourceManager.GetString("BookTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Use English Characters only.
        /// </summary>
        public static string Charactersonly {
            get {
                return ResourceManager.GetString("Charactersonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Publication.
        /// </summary>
        public static string PlaceOfPublication {
            get {
                return ResourceManager.GetString("PlaceOfPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher Name.
        /// </summary>
        public static string PublisherName {
            get {
                return ResourceManager.GetString("PublisherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        public static string Qualifications {
            get {
                return ResourceManager.GetString("Qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The Author&apos;s Name.
        /// </summary>
        public static string Required_AuthorName {
            get {
                return ResourceManager.GetString("Required_AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose The Book Type.
        /// </summary>
        public static string Required_BookTypeId {
            get {
                return ResourceManager.GetString("Required_BookTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The Place of Publication.
        /// </summary>
        public static string Required_PlaceOfPublication {
            get {
                return ResourceManager.GetString("Required_PlaceOfPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The Publisher&apos;s Name.
        /// </summary>
        public static string Required_PublisherName {
            get {
                return ResourceManager.GetString("Required_PublisherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter your  Qualifications.
        /// </summary>
        public static string Required_Qualifications {
            get {
                return ResourceManager.GetString("Required_Qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The Standard Book Number.
        /// </summary>
        public static string Required_StandardBookNumber {
            get {
                return ResourceManager.GetString("Required_StandardBookNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Suggested Book Title.
        /// </summary>
        public static string Required_SuggestedBookTitle {
            get {
                return ResourceManager.GetString("Required_SuggestedBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter your Email.
        /// </summary>
        public static string Required_VisitorEmail {
            get {
                return ResourceManager.GetString("Required_VisitorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter your Phone Number.
        /// </summary>
        public static string Required_VisitorMobile {
            get {
                return ResourceManager.GetString("Required_VisitorMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter your Name.
        /// </summary>
        public static string Required_VisitorName {
            get {
                return ResourceManager.GetString("Required_VisitorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The Year of Publication.
        /// </summary>
        public static string Required_YearOfPublication {
            get {
                return ResourceManager.GetString("Required_YearOfPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Book Number.
        /// </summary>
        public static string StandardBookNumber {
            get {
                return ResourceManager.GetString("StandardBookNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Book Title.
        /// </summary>
        public static string SuggestedBookTitle {
            get {
                return ResourceManager.GetString("SuggestedBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email is invalid, Please! Check it again.
        /// </summary>
        public static string ValidateEmail {
            get {
                return ResourceManager.GetString("ValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Phone Number is invalid, Please! Check it again.
        /// </summary>
        public static string ValidateMobile {
            get {
                return ResourceManager.GetString("ValidateMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string VisitorEmail {
            get {
                return ResourceManager.GetString("VisitorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string VisitorMobile {
            get {
                return ResourceManager.GetString("VisitorMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string VisitorName {
            get {
                return ResourceManager.GetString("VisitorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of Publication.
        /// </summary>
        public static string YearOfPublication {
            get {
                return ResourceManager.GetString("YearOfPublication", resourceCulture);
            }
        }
    }
}
